version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: patch
    rebase-strategy: disabled
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    commit-message:
      prefix: patch
    rebase-strategy: disabled
