---
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena-io/open-balena-registry-proxy
      publish: false
npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "14"
        - "16"
