version: "2"

services:

  proxy:
    image: localhost:5000/sut
    environment:
      PROXY_PORT: 5000
      REGISTRY2_HOST: registry2.balena-cloud.com

  docker:
    image: docker:24.0.5-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: --insecure-registry=http://proxy:5000 --debug --iptables=false
    depends_on:
      - proxy

  sut:
    image: alpine:3.18
    command: >-
      sh -c '
      apk add --no-cache skopeo docker-cli-buildx &&
      sleep 60 &&
      docker build . &&
      docker buildx create --name sut --config /buildkitd.toml --driver-opt network=host --use &&
      docker buildx build --pull . &&
      skopeo inspect docker://proxy:5000/balena/open-balena-registry-proxy --tls-verify=false'
    depends_on:
      - proxy
      - docker
    environment:
      DOCKER_HOST: tcp://docker:2375
    volumes:
      - ./tests/fixtures/src:/src:ro
      - ./tests/fixtures/buildkitd.toml:/buildkitd.toml:ro
    working_dir: /src
