version: "2"

services:

  proxy:
    image: balena/open-balena-registry-proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROXY_PORT: 5000
      REGISTRY2_HOST: registry2.balena-cloud.com

  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: --insecure-registry proxy:5000 --tls=false --debug

  sut:
    image: docker:latest
    command: >-
      sh -c 'while ! docker info; do sleep 1; done;
      docker build . &&
      docker buildx create --name sut --config /buildkitd.toml --driver-opt network=host --use &&
      docker buildx build --pull .'
    depends_on:
      - proxy
      - docker
    environment:
      DOCKER_HOST: tcp://docker:2375
    volumes:
      - ./tests/fixtures/src:/src:ro
      - ./tests/fixtures/buildkitd.toml:/buildkitd.toml:ro
    working_dir: /src
