name: balena

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

env:
  ENVIRONMENT: balena-cloud.com

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@v0.13.1
        with:
          balena_token: ${{ secrets.BALENA_API_KEY_PUSH }}
          fleet: balena/open-balena-registry-proxy
          environment: ${{ env.ENVIRONMENT }}
          versionbot: true
